import 'user_model.dart';

List<UserModel> dummyUsers = [
  UserModel(
    id: "1",
    name: "John Doe",
    isOnline: true,
    lastSeen: "10:00 AM",
    lastMessage: "Hey, how are you?",
    unreadMessageCount: 2,
  ),
  UserModel(
    id: "2",
    name: "Jane Smith",
    isOnline: false,
    lastSeen: "09:30 AM",
    lastMessage: "See you later!",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "3",
    name: "Michael Johnson",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Can we meet tomorrow?",
    unreadMessageCount: 1,
  ),
  UserModel(
    id: "4",
    name: "Emily Davis",
    isOnline: false,
    lastSeen: "Yesterday",
    lastMessage: "Thanks for the update.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "5",
    name: "William Brown",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "I'll check it out.",
    unreadMessageCount: 5,
  ),
  UserModel(
    id: "6",
    name: "Olivia Wilson",
    isOnline: false,
    lastSeen: "11:45 PM",
    lastMessage: "Good night!",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "7",
    name: "James Taylor",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Let's grab lunch.",
    unreadMessageCount: 3,
  ),
  UserModel(
    id: "8",
    name: "Sophia Martinez",
    isOnline: false,
    lastSeen: "2 days ago",
    lastMessage: "Sent the files.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "9",
    name: "Benjamin Anderson",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Sounds good.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "10",
    name: "Isabella Thomas",
    isOnline: false,
    lastSeen: "1 week ago",
    lastMessage: "Happy Birthday!",
    unreadMessageCount: 1,
  ),
  UserModel(
    id: "11",
    name: "Lucas Jackson",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Where are you?",
    unreadMessageCount: 4,
  ),
  UserModel(
    id: "12",
    name: "Mia White",
    isOnline: false,
    lastSeen: "12:15 PM",
    lastMessage: "Call me when you're free.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "13",
    name: "Henry Harris",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Got it.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "14",
    name: "Charlotte Martin",
    isOnline: false,
    lastSeen: "3 days ago",
    lastMessage: "No problem.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "15",
    name: "Alexander Thompson",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "On my way.",
    unreadMessageCount: 2,
  ),
  UserModel(
    id: "16",
    name: "Amelia Garcia",
    isOnline: false,
    lastSeen: "08:00 AM",
    lastMessage: "Did you see that?",
    unreadMessageCount: 1,
  ),
  UserModel(
    id: "17",
    name: "Ethan Martinez",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "LOL",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "18",
    name: "Harper Robinson",
    isOnline: false,
    lastSeen: "Yesterday",
    lastMessage: "I agree.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "19",
    name: "Daniel Clark",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "What do you think?",
    unreadMessageCount: 6,
  ),
  UserModel(
    id: "20",
    name: "Evelyn Rodriguez",
    isOnline: false,
    lastSeen: "4 hours ago",
    lastMessage: "Okay.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "21",
    name: "Matthew Lewis",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Sure thing.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "22",
    name: "Abigail Walker",
    isOnline: false,
    lastSeen: "10:30 PM",
    lastMessage: "Maybe later.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "23",
    name: "Joseph Hall",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Running late.",
    unreadMessageCount: 1,
  ),
  UserModel(
    id: "24",
    name: "Elizabeth Allen",
    isOnline: false,
    lastSeen: "5 minutes ago",
    lastMessage: "I'm here.",
    unreadMessageCount: 0,
  ),
  UserModel(
    id: "25",
    name: "David Young",
    isOnline: true,
    lastSeen: "Online",
    lastMessage: "Let's do it!",
    unreadMessageCount: 3,
  ),
];
